-- Aktuelle Skript-Konfiguration: Oracle

DROP TABLE DWH_METADATEN_ONTOLOGY2;

/* Erzeuge eine weitere Metadaten-Tabelle DWH_METADATEN_ONTOLOGY_SEB, bei der die ungültigen Zeichen herausgefiltert sind,
   um Probleme beim Erzeugen der OWL-Klassen und. -Instanzen zu vermeiden.
   Konventionen:
      - Endet auf "2": Alle ungültigen Zeichen sind entfernt.
      - Endet auf "3": Nur die Gänsefüßchen sind entfernt.
*/

-- Selektiere die Teilmenge an Metadaten, die wirklich benötigt wird:

DROP TABLE DWH_METADATEN_ONTOLOGY_SEB_SEL;
CREATE /*+ APPEND NOLOGGING */  TABLE DWH_METADATEN_ONTOLOGY_SEB_SEL AS
SELECT *
FROM PD_DWH_METADATEN_ONTOLOGY_SEB
--WHERE
-- ...
;

-- Transformiere diese Metadaten um die Strings für die spätere Ontologie vorzubereiten:

DROP TABLE DWH_METADATEN_ONTOLOGY_SEB_TRF ;
CREATE /*+ APPEND NOLOGGING */  TABLE DWH_METADATEN_ONTOLOGY_SEB_TRF AS
SELECT DWH_METADATEN_ONTOLOGY_SEB_SEL.FORMID FORMID,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.FORM_ADMINNAME,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.FORM_ADMINNAME, '[^A-Za-z0-9]','_') FORM_ADMINNAME2,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.FORM_DISPLAYNAME,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.FORM_DISPLAYNAME, '[^A-Za-z0-9]','_') FORM_DISPLAYNAME2,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.FORM_DISPLAYNAME, '["]','') FORM_DISPLAYNAME3,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.FORMVERSION,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.STAGED,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.COMPONENTID,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_ADMINNAME,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_ADMINNAME, '[^A-Za-z0-9]','_') COMP_ADMINNAME2,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_ADMINNAME, '["]','') COMP_ADMINNAME3,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_DISPLAYNAME,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_DISPLAYNAME, '[^A-Za-z0-9]','_') COMP_DISPLAYNAME2,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.COMP_DISPLAYNAME, '["]','') COMP_DISPLAYNAME3,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.COMPONENTVERSION,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.EDITOR,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.CARRYFORWARD,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_INT,
       REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_INT, '[^A-Za-z0-9]','_') OPTIONS_INT2,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_EXP,
       REGEXP_REPLACE(REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_EXP, '[^A-Za-z0-9]', '_'), '([^[:graph:]|^[:blank:]])','') OPTIONS_EXP2,
       REGEXP_REPLACE(REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_EXP, '["]', '_'), '([^[:graph:]|^[:blank:]])','') OPTIONS_EXP3,
       REGEXP_REPLACE(REGEXP_REPLACE(DWH_METADATEN_ONTOLOGY_SEB_SEL.OPTIONS_EXP, '[^A-Za-z0-9]', '_'), '([^[:graph:]|^[:blank:]])','') OPTIONS_EXP4,
       DWH_METADATEN_ONTOLOGY_SEB_SEL.TABORDER      
FROM DWH_METADATEN_ONTOLOGY_SEB_SEL;


-- Erstelle eine Hierarchietabelle über 3 Ebenen:

DROP TABLE FORM_HIERARCHY;
CREATE TABLE FORM_HIERARCHY AS
SELECT DISTINCT A.MAIN_FORMID FORMID_PARENT, A.SUB_FORMID FORMID, B.SUB_FORMID FORMID_CHILD
FROM PD_DWH_NUTZDATEN_FORMCHAPTERS A
FULL OUTER JOIN PD_DWH_NUTZDATEN_FORMCHAPTERS B
ON A.SUB_FORMID = B.MAIN_FORMID;
UPDATE FORM_HIERARCHY SET FORMID_PARENT = NULL WHERE FORMID_PARENT = FORMID;
UPDATE FORM_HIERARCHY SET FORMID_CHILD = NULL WHERE FORMID_CHILD = FORMID;
DELETE FROM FORM_HIERARCHY
WHERE FORMID_PARENT IS NULL 
  AND FORMID IS NOT NULL
  AND FORMID_CHILD IS NULL
  AND FORMID IN (SELECT DISTINCT FORMID FROM FORM_HIERARCHY WHERE FORMID_PARENT IS NOT NULL OR FORMID_CHILD IS NOT NULL);


DROP TABLE DWH_METADATEN_ONTOLOGY2;

CREATE /*+ APPEND NOLOGGING */ TABLE DWH_METADATEN_ONTOLOGY2 AS
SELECT  
DWH_METADATEN_ONTOLOGY_SEB_TRF.FORMID FORMID,
HIR.FORMID_CHILD SUB_FORMID,
DWH_METADATEN_ONTOLOGY_SEB_TRF.FORM_ADMINNAME, DWH_METADATEN_ONTOLOGY_SEB_TRF.FORM_ADMINNAME2, DWH_METADATEN_ONTOLOGY_SEB_TRF.FORM_DISPLAYNAME, DWH_METADATEN_ONTOLOGY_SEB_TRF.FORM_DISPLAYNAME2, DWH_METADATEN_ONTOLOGY_SEB_TRF.FORM_DISPLAYNAME3, DWH_METADATEN_ONTOLOGY_SEB_TRF.FORMVERSION, DWH_METADATEN_ONTOLOGY_SEB_TRF.STAGED, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMPONENTID, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_ADMINNAME, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_ADMINNAME2, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_ADMINNAME3, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_DISPLAYNAME, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_DISPLAYNAME2, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMP_DISPLAYNAME3, DWH_METADATEN_ONTOLOGY_SEB_TRF.COMPONENTVERSION, DWH_METADATEN_ONTOLOGY_SEB_TRF.EDITOR, DWH_METADATEN_ONTOLOGY_SEB_TRF.CARRYFORWARD, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_INT, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_INT2, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_EXP, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_EXP2, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_EXP3, DWH_METADATEN_ONTOLOGY_SEB_TRF.OPTIONS_EXP4, DWH_METADATEN_ONTOLOGY_SEB_TRF.TABORDER 
FROM DWH_METADATEN_ONTOLOGY_SEB_TRF
LEFT JOIN FORM_HIERARCHY HIR
ON HIR.FORMID = DWH_METADATEN_ONTOLOGY_SEB_TRF.FORMID
;

UPDATE DWH_METADATEN_ONTOLOGY2 SET SUB_FORMID = FORMID WHERE SUB_FORMID IS NULL;

DROP TABLE ONTOLOGY_N3;
CREATE TABLE ONTOLOGY_N3 (LINE VARCHAR(4000));
INSERT INTO ONTOLOGY_N3(LINE) VALUES ('soa:Soarian_Item a owl:Class .');

DROP TABLE ONTOLOGY_N3_TARGET;
CREATE TABLE ONTOLOGY_N3_TARGET (LINE VARCHAR(4000));
INSERT INTO ONTOLOGY_N3_TARGET(LINE) VALUES ('soatrgt:Soarian_Item a owl:Class .');
INSERT INTO ONTOLOGY_N3_TARGET(LINE) VALUES ('soatrgt:Soarian_Item rdfs:subClassOf mdr:MDR-Dataelement .');

DROP TABLE ONTOLOGY_N3_MAPPING;
CREATE TABLE ONTOLOGY_N3_MAPPING (LINE VARCHAR(4000));

-- Lege alle Bögen als Unterklassen von Soarian_Item an (Source Ontology):
SELECT '------------------- Bearbeite Bögen -------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID ||' rdfs:subClassOf soa:Soarian_Item .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID ||' soa:hasNiceName "' || FORM_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE FORM_DISPLAYNAME2 IS NOT NULL;

-- Lege alle Bögen als Unterklassen von Soarian_Item an (Target Ontology):
SELECT '------------------- Bearbeite Bögen -------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || FORM_DISPLAYNAME2 || '_' || FORM_ADMINNAME2 || '_' || FORMID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || FORM_DISPLAYNAME2 || '_'|| FORM_ADMINNAME2 || '_' || FORMID ||' rdfs:subClassOf soatrgt:Soarian_Item .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || FORM_DISPLAYNAME2 || '_'|| FORM_ADMINNAME2 || '_' || FORMID ||' soatrgt:hasNiceName "' || FORM_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE FORM_DISPLAYNAME2 IS NOT NULL;


-- Lege Instanzen der Bögen an, über die überprüft werden kann, wann ein Bogen angelegt wurde (Source Ontology):
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || '_angelegt a soa:' || FORM_ADMINNAME2 || '_' || FORMID || ' .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || '_angelegt omsys:hasSelectFilter "(FORMID = ' || FORMID || ' OR FORMID = ' || SUB_FORMID || ')" .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || '_angelegt omsys:hasSelectFilter "ASSESSMENTSTATUS <> 4" .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || '_angelegt omsys:hasSourceTable omsys:ErlangenSTGSoarianTable_FormExistence .' FROM DWH_METADATEN_ONTOLOGY2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || FORM_ADMINNAME2 || '_' || FORMID || '_angelegt a omsys:ProcessedItem .'  FROM DWH_METADATEN_ONTOLOGY2;


-- Lege alle Typ-1-Dokumentations-Elemente als Unterklassen des jeweiligen Bogens an (Source Ontology): 
SELECT '------------------- Klassen für Typ 1-------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NOT NULL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' rdfs:subClassOf soa:' || FORM_ADMINNAME2|| '_' || FORMID ||' .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NOT NULL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' soa:hasNiceName "' || COMP_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE COMP_DISPLAYNAME2 IS NOT NULL AND OPTIONS_INT2 IS NOT NULL;

-- Lege alle Typ-1-Dokumentations-Elemente als Unterklassen des jeweiligen Bogens an (Target Ontology): 
SELECT '------------------- Klassen für Typ 1-------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_'|| COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NOT NULL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_'|| COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' rdfs:subClassOf soatrgt:' || FORM_DISPLAYNAME2 || '_' || FORM_ADMINNAME2|| '_' || FORMID ||' .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NOT NULL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_'|| COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' soatrgt:hasNiceName "' || COMP_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE COMP_DISPLAYNAME2 IS NOT NULL AND OPTIONS_INT2 IS NOT NULL;

-- Lege alle Typ-2-Dokumentations-Elemente als Unterklassen des jeweiligen Bogens an (Source Ontology):
SELECT '------------------- Klassen für Typ 2-------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NULL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' rdfs:subClassOf soa:' || FORM_ADMINNAME2|| '_' || FORMID ||' .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NULL;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' soa:hasNiceName "' || COMP_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE COMP_DISPLAYNAME2 IS NOT NULL AND OPTIONS_INT2 IS NULL;

-- Lege alle Typ-2-Dokumentations-Elemente als Unterklassen des jeweiligen Bogens an (Target Ontology):
SELECT '------------------- Klassen für Typ 2-------------------' AS MESSAGE FROM DUAL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' a owl:Class .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NULL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' rdfs:subClassOf soatrgt:' || FORM_DISPLAYNAME2 || '_' || FORM_ADMINNAME2 || '_' || FORMID ||' .' FROM DWH_METADATEN_ONTOLOGY2 WHERE OPTIONS_INT2 IS NULL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' soa:hasNiceName "' || COMP_DISPLAYNAME3 || '" .' FROM DWH_METADATEN_ONTOLOGY2 WHERE COMP_DISPLAYNAME2 IS NOT NULL AND OPTIONS_INT2 IS NULL;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:' || COMP_DISPLAYNAME2 || '_' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID || ' omsys:hasDataType mdr:Float .' FROM DWH_METADATEN_ONTOLOGY2 WHERE COMP_DISPLAYNAME2 IS NOT NULL AND OPTIONS_INT2 IS NULL;

COMMIT;

-------------------------------------------------------------------
-- Typ 1 Dokumentationselemente (aufzählbar)
-- Alle, außer _DCSMSCheckboxList und _CCTTickBox

SELECT '------------------- Instanzen für Typ 1-------------------' AS MESSAGE FROM DUAL;

DROP TABLE COMPONENT;
CREATE TABLE COMPONENT AS
SELECT FORMID || '_' || COMPONENTID || '_' || MIN(COMPONENTVERSION) || '_' || OPTIONS_INT2 AS SELECTABLEVALUE,
       FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2) AS SELECTABLEVALUE2,
       COMPONENTID,
       COMP_DISPLAYNAME3,
       COMP_ADMINNAME2,
       COMP_ADMINNAME3,
       MIN(COMPONENTVERSION) AS MIN_COMPONENTVERSION,
       MAX(COMPONENTVERSION) AS MAX_COMPONENTVERSION,
       OPTIONS_INT2,
       OPTIONS_EXP3,
       OPTIONS_EXP4,
       FORMID,
       SUB_FORMID,
       EDITOR
FROM DWH_METADATEN_ONTOLOGY2
WHERE OPTIONS_INT2 IS NOT NULL
AND EDITOR != '_DCSMSCheckboxList' AND EDITOR != '_CCTTickBox'
GROUP BY SUB_FORMID, FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2), COMPONENTID, COMP_DISPLAYNAME3, COMP_ADMINNAME2, COMP_ADMINNAME3, OPTIONS_INT2, OPTIONS_EXP3, FORMID, EDITOR,  OPTIONS_EXP4
ORDER BY COMPONENTID, MIN_COMPONENTVERSION, OPTIONS_INT2;

-- Jedes Dokumentationselement ist eine Instanz der Klasse ...
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a soa:' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- ... und ein ProcessedItem:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a omsys:ProcessedItem .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- Lege für die Dokumentationselemente nun alle DatatypeProperties an:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasAttribute "'|| COMP_DISPLAYNAME3 || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasValue "'''|| REPLACE(OPTIONS_EXP3, '[CR-LF]', ' ')|| '''" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMinComponentVersion "'|| MIN_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMaxComponentVersion "'|| MAX_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasEditor "'|| EDITOR || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE = ''' || OPTIONS_EXP3 || '''" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "COMPONENTID = '|| COMPONENTID || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "(FORMID = ' || FORMID || ' OR FORMID = ' || SUB_FORMID || ')" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "ASSESSMENTSTATUS <> 4" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSourceTable omsys:ErlangenSTGSoarianTable .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE IS NOT NULL" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE != '' ''" .' FROM COMPONENT;


-- Target Ontology:
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || A.OPTIONS_EXP4 || '_' || A.SELECTABLEVALUE ||' rdfs:subClassOf soatrgt:' || B.COMP_DISPLAYNAME2 || '_' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4 || '_' || SELECTABLEVALUE ||' a owl:Class .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4 || '_' || SELECTABLEVALUE ||' soatrgt:hasNiceName "'|| OPTIONS_EXP3 || '" .' FROM COMPONENT;
-- Mapping Ontology:
INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4 || '_' || SELECTABLEVALUE ||' omsys:hasImport soa:Value' || SELECTABLEVALUE || ' .' FROM COMPONENT;


-------------------------------------------------------------------
-- Typ 1 Dokumentationselemente (aufzählbar)
-- Nur _DCSMSCheckboxList (Mehrfachauswahl)


SELECT '------------------- Instanzen für Typ 1-------------------' AS MESSAGE FROM DUAL;

DROP TABLE COMPONENT;
CREATE TABLE COMPONENT AS
SELECT FORMID || '_' || COMPONENTID || '_' || MIN(COMPONENTVERSION) || '_' || OPTIONS_INT2 AS SELECTABLEVALUE,
       FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2) AS SELECTABLEVALUE2,
       COMPONENTID,
       COMP_DISPLAYNAME3,
       COMP_ADMINNAME2,
       COMP_ADMINNAME3,
       MIN(COMPONENTVERSION) AS MIN_COMPONENTVERSION,
       MAX(COMPONENTVERSION) AS MAX_COMPONENTVERSION,
       OPTIONS_INT2,
       OPTIONS_EXP3,
       OPTIONS_EXP4,
       FORMID,
       SUB_FORMID,
       EDITOR
FROM DWH_METADATEN_ONTOLOGY2
WHERE OPTIONS_INT2 IS NOT NULL
AND EDITOR = '_DCSMSCheckboxList'
GROUP BY SUB_FORMID, FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2), COMPONENTID, COMP_DISPLAYNAME3, COMP_ADMINNAME2, COMP_ADMINNAME3, OPTIONS_INT2, OPTIONS_EXP3, FORMID, EDITOR, OPTIONS_EXP4
ORDER BY SUB_FORMID,COMPONENTID, MIN_COMPONENTVERSION, OPTIONS_INT2;

-- Jedes Dokumentationselement ist eine Instanz der Klasse ...
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a soa:' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- ... und ein ProcessedItem:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a omsys:ProcessedItem .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- Lege für die Dokumentationselemente nun alle DatatypeProperties an:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasAttribute "'|| COMP_DISPLAYNAME3 || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasValue "'''|| REPLACE(OPTIONS_EXP3, '[CR-LF]', ' ') || '''" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMinComponentVersion "'|| MIN_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMaxComponentVersion "'|| MAX_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasEditor "'|| EDITOR || '" .' FROM COMPONENT;

-- Oracle:
--INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "INSTR(VALUE, ''' || OPTIONS_EXP3 || ''') > 0" .' FROM COMPONENT;
-- MSSQL:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "CHARINDEX(''' || OPTIONS_EXP3 || ''', VALUE) > 0" .' FROM COMPONENT;

INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "COMPONENTID = '|| COMPONENTID || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "(FORMID = ' || FORMID || ' OR FORMID = ' || SUB_FORMID || ')" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "ASSESSMENTSTATUS <> 4" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSourceTable omsys:ErlangenSTGSoarianTable .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE IS NOT NULL" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE != '' ''" .' FROM COMPONENT;

---- Target Ontology:
--INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value' || A.SELECTABLEVALUE ||' rdfs:subClassOf soatrgt:' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
--FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
--WHERE A.COMPONENTID = B.COMPONENTID
--AND A.FORMID = B.FORMID;
--INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value' || SELECTABLEVALUE ||' a owl:Class .' FROM COMPONENT;
--INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value' || SELECTABLEVALUE ||' soatrgt:hasNiceName "'|| OPTIONS_EXP3 || '" .' FROM COMPONENT;
---- Mapping Ontology:
--INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:Value' || SELECTABLEVALUE ||' omsys:hasImport soa:Value' || SELECTABLEVALUE || ' .' FROM COMPONENT;


-- Target Ontology:
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || A.OPTIONS_EXP4 || '_' || A.SELECTABLEVALUE  ||' rdfs:subClassOf soatrgt:' || B.COMP_DISPLAYNAME2 || '_' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4  || '_' || SELECTABLEVALUE  ||' a owl:Class .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3_TARGET SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4  || '_' || SELECTABLEVALUE ||' soatrgt:hasNiceName "'|| OPTIONS_EXP3 || '" .' FROM COMPONENT;
-- Mapping Ontology:
INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:Value_' || OPTIONS_EXP4  || '_' || SELECTABLEVALUE ||' omsys:hasImport soa:Value' || SELECTABLEVALUE || ' .' FROM COMPONENT;

-------------------------------------------------------------------
-- Typ 1 Dokumentationselemente (aufzählbar)
-- Nur _CCTTickBox

SELECT '------------------- Instanzen für Typ 1-------------------' AS MESSAGE FROM DUAL;

DROP TABLE COMPONENT;
CREATE TABLE COMPONENT AS
SELECT FORMID || '_' || COMPONENTID || '_' || MIN(COMPONENTVERSION) || '_' || OPTIONS_INT2 AS SELECTABLEVALUE,
       FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2) AS SELECTABLEVALUE2,
       COMPONENTID,
       COMP_DISPLAYNAME3,
       COMP_ADMINNAME2,
       COMP_ADMINNAME3,
       MIN(COMPONENTVERSION) AS MIN_COMPONENTVERSION,
       MAX(COMPONENTVERSION) AS MAX_COMPONENTVERSION,
       OPTIONS_INT2,
       OPTIONS_EXP3,
       OPTIONS_EXP4,
       FORMID,
       SUB_FORMID,
       EDITOR
FROM DWH_METADATEN_ONTOLOGY2
WHERE OPTIONS_INT2 IS NOT NULL
AND EDITOR = '_CCTTickBox'
GROUP BY SUB_FORMID,FORMID || '_' || COMPONENTID || '_' || UPPER(OPTIONS_EXP2), COMPONENTID, COMP_DISPLAYNAME3, COMP_ADMINNAME2, COMP_ADMINNAME3, OPTIONS_INT2, OPTIONS_EXP3, FORMID, EDITOR, OPTIONS_EXP4
ORDER BY COMPONENTID, MIN_COMPONENTVERSION, OPTIONS_INT2;

-- Jedes Dokumentationselement ist eine Instanz der Klasse ...
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a soa:' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- ... und ein ProcessedItem:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a omsys:ProcessedItem .' 
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;


-- Lege für die Dokumentationselemente nun alle DatatypeProperties an:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasAttribute "'|| COMP_DISPLAYNAME3 || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasValue "'''|| regexp_replace(OPTIONS_EXP3,'([^[:graph:]|^[:blank:]])','') || '''" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMinComponentVersion "'|| MIN_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMaxComponentVersion "'|| MAX_COMPONENTVERSION || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasEditor "'|| EDITOR || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "(VALUE = ''True'' OR VALUE = ''Ja'' OR VALUE = ''Yes'')" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "COMPONENTID = '|| COMPONENTID || '" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "(FORMID = ' || FORMID || ' OR FORMID = ' || SUB_FORMID || ')" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "ASSESSMENTSTATUS <> 4" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSourceTable omsys:ErlangenSTGSoarianTable .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE IS NOT NULL" .' FROM COMPONENT;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE != '' ''" .' FROM COMPONENT;

-- Mapping Ontology:
--INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:Value' || SELECTABLEVALUE ||' omsys:hasImport soa:Value' || SELECTABLEVALUE || ' .' FROM COMPONENT;

INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:' || B.COMP_DISPLAYNAME2 || '_' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' omsys:hasImport soa:Value' || A.SELECTABLEVALUE || '. '
FROM COMPONENT A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;


-------------------------------------------------------------------
-- Typ 2 Dokumentationselemente (nicht aufzählbar)

SELECT '------------------- Instanzen für Typ 2-------------------' AS MESSAGE FROM DUAL;
DROP TABLE COMPONENT2;
CREATE TABLE COMPONENT2 AS
SELECT FORMID || '_' || COMPONENTID || '_' || MIN(COMPONENTVERSION) AS SELECTABLEVALUE,
       FORMID || '_' || COMPONENTID AS SELECTABLEVALUE2,
       COMPONENTID,
       COMP_DISPLAYNAME3,
       COMP_ADMINNAME2,
       COMP_ADMINNAME3,
       MIN(COMPONENTVERSION) AS MIN_COMPONENTVERSION,
       MAX(COMPONENTVERSION) AS MAX_COMPONENTVERSION,
       OPTIONS_INT2,
       OPTIONS_EXP3,
       OPTIONS_EXP4,
       FORMID,
       SUB_FORMID,
       EDITOR
FROM DWH_METADATEN_ONTOLOGY2
WHERE OPTIONS_INT2 IS NULL
GROUP BY SUB_FORMID,FORMID || '_' || COMPONENTID, COMPONENTID, COMP_DISPLAYNAME3, COMP_ADMINNAME2, COMP_ADMINNAME3, OPTIONS_INT2, OPTIONS_EXP3, FORMID, EDITOR, OPTIONS_EXP4
ORDER BY COMPONENTID, MIN_COMPONENTVERSION, OPTIONS_INT2;

-- Jedes Dokumentationselement ist eine Instanz der Klasse ...
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a soa:' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' .' 
FROM COMPONENT2 A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- ... und ein ProcessedItem:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || A.SELECTABLEVALUE ||'  a omsys:ProcessedItem .' 
FROM COMPONENT2 A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;

-- Lege für die Dokumentationselemente nun alle DatatypeProperties an:
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasAttribute "'|| COMP_DISPLAYNAME3 || '" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMinComponentVersion "'|| MIN_COMPONENTVERSION || '" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasMaxComponentVersion "'|| MAX_COMPONENTVERSION || '" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' soa:hasEditor "'|| EDITOR || '" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "COMPONENTID = '|| COMPONENTID || '" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "(FORMID = ' || FORMID || ' OR FORMID = ' || SUB_FORMID || ')" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "ASSESSMENTSTATUS <> 4" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSourceTable omsys:ErlangenSTGSoarianTable .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE IS NOT NULL" .' FROM COMPONENT2;
INSERT INTO ONTOLOGY_N3 SELECT DISTINCT 'soa:Value' || SELECTABLEVALUE ||' omsys:hasSelectFilter "VALUE != '' ''" .' FROM COMPONENT2;

--INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:' || COMP_ADMINNAME2 || '_' || FORMID || '_' || COMPONENTID ||' omsys:hasImport soa:Value' || SELECTABLEVALUE || ' .' FROM COMPONENT2;

INSERT INTO ONTOLOGY_N3_MAPPING SELECT DISTINCT 'soatrgt:' || B.COMP_DISPLAYNAME2 || '_' || B.COMP_ADMINNAME2 || '_' || B.FORMID || '_' || B.COMPONENTID || ' omsys:hasImport soa:Value' || A.SELECTABLEVALUE || '. '
FROM COMPONENT2 A, DWH_METADATEN_ONTOLOGY2 B
WHERE A.COMPONENTID = B.COMPONENTID
AND A.FORMID = B.FORMID;


COMMIT;

